#!/usr/bin/env php
<?php
	require __DIR__.'/vendor/autoload.php';

	use Tilwa\Modules\CliRunner;

	use Tilwa\Adapters\Console\SymfonyCli;

	use public\MyApp;

	$runner = new CliRunner (new MyApp, new SymfonyCli("Suphle", "v2"));

	$runner->loadCommands();

	$runner->awaitCommands();
?>