<?php
	namespace Tilwa\Contracts\IO\Image;

	use Psr\Http\Message\UploadedFileInterface;

	interface InferiorImageClient {
		
		public function setupClient ():void;

		public function downgrade (string $currentPath):void;

		/**
		 * @param {newPath} Can be omitted if that value is to be generated by the underlying client
		 * 
		 * * @return Location of saved file
		*/
		public function moveDowngraded (UploadedFileInterface $image, string $newPath):string;
	}
?>