<?php
	namespace Tilwa\Contracts\IO;

	use Psr\Http\Message\UploadedFileInterface;

	interface ImageSaver {

		/**
		 * @param {operationName} thumbnail|optimize
		 * 
		 * @return string|null when name is to be generated by upload client
		*/
		public function resolveName (UploadedFileInterface $file, string $operationName, string $resourceName):?string;

		/**
		 * @param {images} UploadedFileInterface[]
		 * @param {resourceName} e.g. profile_photo
		 * 
		 * @return Array of saved filenames
		*/
		public function transportImages (array $images, string $operationName, string $resourceName):array;

		/**
		 * @param {images} UploadedFileInterface[] Array will be keyed by resolved file name. So, no additional need to call [resolveName]. Impossible for [transportImages] since names may be dictated by the underlying transport client
		*/
		public function transportImagesAsync (array $images):void;

		/**
		 * Requires [resolveName] to return a value
		*/
		public function savesAsync ():bool;
	}
?>