<?php

namespace Suphle\Contracts\IO\Image;

use Symfony\Component\HttpFoundation\File\UploadedFile;

interface InferiorImageClient
{
    /**
     * @param {newPath} Can be omitted if that value is to be generated by the underlying client
     *
     * @return Location of saved file
    */
    public function downgradeImage(UploadedFile $image, string $newPath, int $maxSize): string;
}
